name: Backend CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'

    - name: Install dependencies
      run: npm install

    - name: Set environment variables
      run: |
        if [ "${{ github.ref }}" = "refs/heads/main" ]; then
          echo "Setting production environment"
          cp .env.production .env
        else
          echo "Setting development environment"
          cp .env.development .env
        fi

    - name: Build
      run: npm run build

    - name: Prepare deployment package
      if: github.ref == 'refs/heads/main'
      run: |
        mkdir -p deploy
        cp -r src deploy/
        cp package.json deploy/
        cp package-lock.json deploy/
        cp .env.production deploy/.env
        cp web.config deploy/

    - name: Deploy to Azure Web App
      if: github.ref == 'refs/heads/main'
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'livestreamingclaims-hpaedbd6b6gbhkb0'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./deploy
        slot-name: 'production'